blank_issues_enabled: false
contact_links:
  - name: Features, Bug Reports, Questions
    url: https://github.com/microsoft/devsquad-copilot/discussions/new/choose
    about: Use Discussions first. This is our preferred starting point for questions, suggestions, and bug reports.